### PR TITLE
Namespace changed?

### PR DESCRIPTION
**Pull request by vicary**

### CODE REVIEW

**Comment by overtrue** [comment]
3.x 没有改名称空间

**Comment by vicary** [comment]
My bad. Do you mean as of `~4.0` `EasyWeChat\BasicService\*` is no longer meant to be used directly?

**Comment by mingyoung** [comment]
@vicary 一般来说这样使用即可 `Factory::officialAccount()->jssdk;`

**Comment by vicary** [comment]
@mingyoung Thank you.

We are extending the `payment` jssdk for a weimob provider, I am kind of touching the abstraction layers here.

**Pull request closed without merging**
